language: julia

os:
  - linux
dist: bionic

julia:
  - 1.1
  - nightly

matrix:
 allow_failures:
 - julia: nightly

notifications:
  email: false

before_install:
  - sudo apt-get install python3 python3-pip
  - pip3 install git+https://github.com/bitcraze/crazyflie-lib-python.git

after_success:
  # push coverage results to Codecov
- julia -e 'using Pkg; cd(Pkg.dir("Crazyflie")); Pkg.add("Crazyflie"); using Coverage; Codecov.submit(Codecov.process_folder())'
